[application]

# App (Project) Name
name = "translator"

[web.app]

# HTML title tag content
title = "Translator"

[bundle]
icon = [
    "../assets/favicon.png",
    "../assets/favicon.ico"
]
identifier = "com.dioxuslabs"
publisher = "DioxusLabs"
icon_path = "../assets/favicon.png"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []


[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
